[workspace]
members = [
    "apps/qualification/canister",
    "apps/qualification/runner",
    "apps/tooling",
    "crates/ic-auth",
    "crates/ic-auth-protocol-types",
]
resolver = "3"

[workspace.package]
version = "0.2.8"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dragginzgame/ic-auth"

[workspace.dependencies]
candid = { version = "0.10", default-features = false }
ic-agent = { version = "0.49.2", default-features = false }
ic-auth = { path = "crates/ic-auth" }
ic-auth-protocol-types = { version = "0.2.8", path = "crates/ic-auth-protocol-types" }
ic-canister-sig-creation = "1.3.1"
ic-cdk = "0.20.3"
ic-certification = "3.2"
ic-host-fs = { version = "0.10", default-features = false }
ic-signature-verification = "0.3"
ic-testkit = "0.28"
ic-verify-bls-signature = { version = "0.6", default-features = false, features = ["alloc"] }
k256 = { version = "0.13.4", default-features = false, features = ["ecdsa"] }
leb128 = "0.2"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }

[workspace.lints.rust]
unsafe_code = "forbid"
