[workspace]
members = ["crates/ic-auth", "crates/ic-auth-protocol-types"]
resolver = "3"

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dragginzgame/ic-auth"

[workspace.dependencies]
candid = { version = "0.10", default-features = false }
ic-auth-protocol-types = { version = "0.1.2", path = "crates/ic-auth-protocol-types" }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
thiserror = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
