[package]
name = "ic-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Canonical application authentication protocol encoding"
publish = false

[dependencies]
ic-auth-types.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
