[package]
name = "ic-auth-protocol-types"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Passive application authentication protocol contracts"
publish = ["crates-io"]

[dependencies]
candid.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
